# general settings
name: Finetune_SloMoBlur_Restormer
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode, adjust based on available GPUs
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: SloMoBlur_TrainSet
    type: Dataset_PairedImage
    # Adjust paths based on your dataset structure
    # If you have Dataset/SloMoBlur/train/blurred and Dataset/SloMoBlur/train/groundtruth:
    dataroot_gt: ./Dataset/SloMoBlur/0_9999/groundtruth
    dataroot_lq: ./Dataset/SloMoBlur/0_9999
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [4, 2, 1]             # Batch size per gpu   
    iters: [10000, 5000, 5000]
    gt_size: 256   # Max patch size for progressive training
    gt_sizes: [128, 192, 256]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    # mini_batch_sizes: [4]   
    # iters: [20000]
    # gt_size: 128   
    # gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: SloMoBlur_ValSet
    type: Dataset_PairedImage
    dataroot_gt: ./Dataset/SloMoBlur/0_9999/groundtruth
    dataroot_lq: ./Dataset/SloMoBlur/0_9999
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4,6,6,8]
  num_refinement_blocks: 4
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False


# path
path:
  # Load pretrained motion deblurring model
  pretrain_network_g: ./Motion_Deblurring/pretrained_models/motion_deblurring.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 20000  # Reduced for finetuning
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Finetuning with lower learning rate
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [20000]       
    restart_weights: [1]
    eta_mins: [0.00001]   # Lower minimum LR for finetuning
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 1e-4  # Lower learning rate for finetuning
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 8
  val_freq: !!float 2e3
  save_img: false
  rgb2bgr: true
  use_image: true
  max_minibatch: 4

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

